name: GitHub Actions Demo
run-name: ${{ github.actor }} is testing out GitHub Actions 🚀
on: [push]
jobs:
  Explore-GitHub-Actions:
    runs-on: ubuntu-latest
    steps:
       - name: Checkout Repository
         uses: actions/checkout@v7.0.1

       - name: List Files
         run: ls -l

       - name: Run Script
         run: |
            chmod +x cowsay-install.sh
            ./cowsay-install.sh
