name: GitHub Actions Demo
run-name: ${{ github.actor }} is testing out GitHub Actions 🚀
on: [push]
jobs:
  Explore-GitHub-Actions:
    runs-on: ubuntu-latest
    steps:
      - name: Install Cowsay
        run:  |
          sudo apt update
          sudo apt install cowsay -y

      - name: Run Cowsay
        run: /usr/games/cowsay "Hello From Github Actions!"

      - name: Use Custom Character
        run: /usr/games/cowsay -f dragon "I am a dragon." >> dragon.txt

      - name: Verify Output
        run: grep -i "dragon" dragon.txt

      - name: Display file
        run: cat dragon.txt

      - name: List file
        run: ls -ltra
